import { Component, OnInit } from '@angular/core';

declare var $: any;
// Si uso declare var viz  da error porque no esta declarada como global
let viz;
declare var tableau;

@Component({
  selector: 'app-gastos-por-economico',
  templateUrl: './gastos-por-economico.component.html',
  styleUrls: ['./gastos-por-economico.component.css']
})
export class GastosPorEconomicoComponent implements OnInit {
  datos;
  // datosJson;
  vez = 0;

  constructor() {
  // C:\Users\pc\Google Drive\Ayuntamiento\Presupuestos\Tablas
    // Tabla economico 2019.xlsx
    // this.datosJson = "";
    // Shift-Alt-I will put a cursor at the end of all selected lines

    this.datos =
    [
      'A CIRJESA-Circuito de Jerez',
      'A Diputaciones, Consejos y cabildos',
      'A EMUVIJESA-Gestión urbanistica',
      'A entes públicos y sociedades mercantiles de la Entidad Local',
      'A Entidades Locales Autónomas',
      'A la Administración General de las Comunidades Autónomas',
      'A la Administración General del Estado',
      'A otras entidades agrupen municipios',
      'A otros subsectores',
      'A/C restauración y rehabilitación sala Profundis Claustros de Santo Domingo',
      'Acción social',
      'Actividades complementarias',
      'Actividades convivencia intercultural',
      'Actividades culturales en barriadas rurales',
      'Actividades culturales y deportivas',
      'Actividades de juventud',
      'Actividades Día Mundial Discapacidad',
      'Actividades Institucionales',
      'Actividades menores p. Infanc Fam.',
      'Actividades programa participación y solidaridad',
      'Actividades programa prevención mendicidad infantil',
      'Actuaciones consolidación Palacio Villapanes',
      'Actuaciones en aseos CEIP Guadalete ELA El Torno',
      'Actuaciones en El Alcazar',
      'Actuaciones en piscina municipal ELA Torrecera',
      'Actuaciones inmediatas',
      'Actuaciones medioambientales cementerio municipal',
      'Actuaciones PMS- Cerrofruto',
      'Actuaciones varias',
      'Actuaciones varias en Claustros de Santo Domingo',
      'Adaptación de viales públicos de la ELA Guadalcacín',
      'Adecent y reparación edificio consistorial ELA Estella del Marques',
      'Adecentamiento de vías públicas ELA Estella del Marqués',
      'Adecuación espacios libres calle Taxdirt',
      'Adecuación espacios públicos entorno centro comercial Area Sur',
      'Adecuación infraestructuras CEIP Guadalete en ELA El Torno',
      'Adquisición elementos de transporte',
      'Adquisición equipo informatico',
      'Adquisición equipos análisis',
      'Adquisición máquina recogida residuos ELA Estella del Marqués',
      'Adquisicion maquinaria, instalaciones y utillaje',
      'Adquisicion material de transporte',
      'Adquisiciones en delimitaciones de areas',
      'Agua',
      'AJEMSA- Serv. agua, alcantarillado y recogida de residuos',
      'Al exterior',
      'Alumbrado decorativo fiestas',
      'Alumbrado decorativo Navidad',
      'Amortización prestamos a medio y largo entes fuera sector público',
      'Amortización prestamos largo plazo entes sector público',
      'Anticipos reintegros al personal a largo plazo',
      'Anticipos reintegros al personal a largo plazo',
      'Aparatos biosaludables parques urbanos	Nuevo en ejecucion 04.04.201',
      'Arrendamiento de maquinaria, instalaciones y utillaje',
      'Arrendamiento material transporte',
      'Arrendamiento otro inmovilizado material',
      'Arrendamientos de equipos para proceso de informacion',
      'Arrendamientos de mobiliario y enseres',
      'Arrendamientos edificios y otras construcciones',
      'Asfaltado de viales públicos de la ELA La Barca de la Florida',
      'Asociación de Ciudades Interculturales',
      'Atencion a la ciudadania en distritos',
      'Atencion sociales en interes de la ciudad',
      'Atenciones benéficiencia y asistencia',
      'Atenciones protocolarias y representativas',
      'Ayuda domiciliaria',
      'Ayudas a banda de música',
      'Ayudas a Bono-Taxi',
      'Ayudas sociales alquiler',
      'Balizamiento y B.R.V.',
      'Banco de alimentos',
      'Cambio luminaria pública a LED piscina municipal ELA El Torno',
      'Campaña contra la violencia de género',
      'Campo de futbol 7 barriada La Granja',
      'Canalizaciones vía pública',
      'Cánones',
      'Cargas urbanisticas',
      'Centro acogida inmigrantes (CEAIN)',
      'Centro de Arte Contemporáneo Callejón de los Bolos',
      'Centro de día Hogar San Juan',
      'CIRJESA-Circuito de Jerez',
      'Claustros de Santo Domingo',
      'Climatizacion de instalaciones',
      'Club Amigos del Zoo',
      'Colegio Oficial Veterinarios de Cádiz',
      'Combustibles y carburantes',
      'Comedor El Salvador',
      'Complemento destino personal funcionario',
      'Complemento específico personal funcionario',
      'COMUJESA',
      'Comunidad de propietarios',
      'Conexión con sistema general viario U.E. 2Q1 Arroyo Membrillar',
      'Consejo Económico y Social',
      'Conservación señalización horizontal, vertical y balizamiento',
      'Conservacion y mantenimiento en mercado central de abastos',
      'Conservación y mantenimiento planta compostaje y reciclaje',
      'Consorcio Bomberos Provincia Cádiz',
      'Consorcio Metropolitano Transporte Bahia Cádiz',
      'Consorcio Metropolitano Transporte Bahía Cádiz',
      'Construcción de centro europeo de la musica andalusi',
      'Construcción de glorieta en A-4 accesos al sector sup 34',
      'Construcción vestuarios adaptados instalaciones deportivas ELA San Isidro',
      'Control tarjetas O.R.A.',
      'Contrucción nave cobertizo instalaciones deportivas ELA San Isidro',
      'Convenio AFEMEN',
      'Convenio APESORJE',
      'Convocatoria unica de subvenciones',
      'Coordinadora ONGDS de la provincia de Cádiz',
      'Cruz Roja Jerez (UMES)',
      'Cruz Roja -Transporte',
      'Custodia, depósito y almacenaje',
      'Del personal directivo',
      'Del personal no directivo',
      'Dietas del personal directivo',
      'Dietas del personal no directivo',
      'Dietas miembros de los organos de gobierno',
      'Dinamización asociaciones',
      'Dinamización del ocio juvenil',
      'Dotación mobiliario infantil y urbano parques ELA Nueva Jarilla',
      'Ecomercado',
      'Economato San Juan de Dios',
      'Edificios y otras construcciones',
      'EDUSI',
      'Ejecución aval UE 4G4B Pago Perceba',
      'EMEMSA-Montes de Propios',
      'EMUVIJESA-Promoción y Gestión de vivienda oficial',
      'Energía eléctrica',
      'Equipamiento Sala Paúl',
      'Equipo fotografico digital',
      'Equipos para procesos de información',
      'Escuela negocios de Jerez',
      'Escultura rotonda de Cuatro Caminos',
      'Estudios y trabajos técnicos',
      '"Expediente reparcelación de la U.E. 4.A.4 ""Entrevías"""',
      '"Expediente reparcelación de la U.E. 4.S.2 ""San Jerónimo B"""',
      '"Expediente reparcelación de la U.E. 4.S1 ""San Jerónimo A"""',
      'Expropiación forzosa Poligono 4 PAU 1 Fdo. Portillo',
      'Festejos populares',
      'Fondo compensación ELA por crecimiento habitantes desde convenio vigente',
      'Fondo Contingencia de Ejecución Presupuestaria (Art.31 LOEPSF)',
      'Fondo estatatal para el empleo y sostenibilidad local',
      'Formación y perfeccionamiento del personal',
      'Fundación Andrés de Ribera',
      'Fundación Caballero Bonald',
      'Fundacion centro acogida San Jose',
      'Fundación Centro Acogida San José',
      'Fundación Municipal de Formación y Empleo',
      'Fundación Secretariado General Gitano',
      'Fundación Teatro Villamarta',
      'Fundaciones',
      'Fundarte ',
      'Gastos diversos',
      'Gastos diversos proyecto casa mujeres',
      'Gastos en aplicaciones informáticas',
      'Gastos formalización,modificación y cancelación operaciones en euros',
      'Gestion ayudas sociales especie',
      'Gratificaciones',
      'Grupo desarrollo rural',
      'Horas extraordinarias personal laboral fijo',
      'Indefinidos no fijos en plantilla',
      'Indemnizaciones',
      'Indemnizaciones ERE',
      'Informáticas',
      'Instalación areas de recreo infantil en diferentes zonas de Jerez',
      'Instalación cesped artifical campo futbol Picadueñas',
      'Instalación de circuitos biosaludables en espacios públicos',
      'Instalacion maquinaria aire acondicionado Casa de la Mujer II fase',
      'Intereses de demora',
      'Intereses de demora a acreedores públicos',
      'Intereses de demora a acreedores públicos otros',
      'Intereses préstamo interior',
      'Inversión reposición maquinaria, instalaciones y utillaje-Instalaciones',
      'Inversión, reposición edificios y otras construcciones',
      'Inversiones asociadas a actuaciones urbanísticas',
      'Inversiones en instalaciones y pistas',
      'JECOMUSA-Servicio de radio y television Municipal',
      'JEREYSSA-Servicio de Recaudación',
      'JESYTEL-Servicios Informaticos Internos',
      'Jurídicos, contenciosos',
      'Limpieza colegios públicos',
      'Limpieza dependencias municipales',
      'Limpieza y aseo',
      'Locomocion de miembros organos gobierno',
      'Mancomunidad municipios Bahía Cádiz',
      'Mantenimiento alarmas',
      'Mantenimiento alumbrado público',
      'Mantenimiento de fuentes ornamentales',
      'Mantenimiento de parques infantiles',
      'Mantenimiento extintores',
      'Mantenimiento parques y jardines públicos',
      'Mantenimiento red semafórica',
      'Mantenimiento señalización horizontal',
      'Mantenimiento señalización vertical',
      'Mantenimiento y alquiler WC botellodromo',
      'Manutención de animales.',
      'Maquinaria, instalaciones y utillaje',
      'Material informático no inventariable',
      'Mejoras alumbrado público ELA Estella del Marqués',
      'Mobiliario y enseres',
      'Museo de la Ciudad de Jerez',
      'Obras accesibilidad 2005. Convenio IMSERSO Y ONCE',
      '"Obras de urbanización calle C - UE 4Q1 ""El Portal"""',
      'Obras Fondo Estatal de Inversión Local',
      'Obras Plan Urban',
      'Obras POS',
      'Operaciones de intercambio financiero',
      'Ordenanzas Reg. Fomento desarrollo económico Jerez',
      'Ordinario no inventariable',
      'Ordinario no inventariable para almacen',
      'Otras indemnizaciones',
      'Otras inversiones de reposición asociadas al funcionamiento operativo',
      'Otras inversiones en infraestructuras',
      'Otras inversiones financ.con ejecución avales',
      'Otras inversiones nuevas en infraestructuras y bienes para u',
      'Otras inversionesnuevas asociadas funcionamiento operativo servicio',
      'Otras obras conexión norte',
      'Otras remuneraciones',
      'Otras remuneraciones personal eventual-Grupos Políticos',
      'Otras remuneraciones personal laboral fijo',
      'Otras subvenciones a empresas privadas',
      'Otras subvenciones a entes públicos y sociedades mercantiles',
      'Otras transferencias',
      'Otras transferencias de capital',
      'Otros complementos personal funcionario',
      'Otros gastos de promoción',
      'Otros gastos diversos',
      'Otros gastos en comunicaciones',
      'Otros gastos financieros',
      'Otros suministros',
      'Otros trabajos realizados por otras empresas y profesionales',
      'Parque flotante desmontable',
      'Patronato Municipal Parque Zoológico',
      'Plan de actuación en colegios pedanias',
      'Plan especial San Juan de Dios',
      'Plan Promoción de Empleo',
      'Por obras a cargo de terceros',
      'POS 2006 Asfaltado varias calles en Nueva Jarilla',
      'Postales',
      'Postales otras',
      'Premios, becas y pensiones de estudio',
      'Prensa, revistas, libros y otras publicaciones',
      'Presupuestos participativos pendientes ejecución anterior',
      'Primas de seguro',
      'Productividad',
      'Productos alimenticios',
      'Productos de limpieza y aseo',
      'Productos farmaceuticos y material sanitario',
      'Programa individual atención',
      'Programa municipal prevención acciones',
      'Programa plan zona sur no subvencionado',
      'Programa subvencionado zonas',
      'Programa transf. ',
      'Programa voluntariado',
      'Programas actuacion en distritos',
      'Proyecto Hombre',
      'Proyecto salud nuestra ciudad',
      'Proyectos modificados y liquidaciones obras convenio educación',
      'Publicación en Diarios Oficiales',
      'Publicidad y propaganda',
      'Publicidad, propaganda a cargo particulares',
      'Puesta en valor del Cine Astoria',
      'Recogida de residuos urbanos',
      'Reforma de infraestructuras en barriada ICOVESA',
      'Refuerzo de firme varias calles',
      'Rehabilitación antiguas escuelas de la ELA Torrecera',
      'Rehabilitación piscina municipal ELA Torrecera',
      'Rehabilitacion techos de galeria soportales de Madre de Dios',
      'Rehabilitacion y mejoras parque y pistal padel ELA La Barca de la Florida',
      'Rehabilitacion y mejoras zonas deportivas ELA San Isidro',
      'Rehabilitacioón centro cultural ELA Estella del Marqués',
      'Remodelacion edificio junto estacion tren (imprenta municipal)',
      'Remodelacion vial glorieta Cuatro Caminos con nudo enlace N-',
      'Reordenación de Plaza Belén',
      'Reparacion edificio gimnasio Campo de la Juventud',
      'Reparación mantenimiento y conservación instrumentos municipales',
      'Reparación saneamiento vía pública ELA Guadalcacin',
      'Reparación sistema electronio campo futbol ELA Guadalcacin',
      'Reparación, mantenimiento y conservación aparatos aire acondicionado',
      'Reparación, mantenimiento y conservación edificios y otras construcciones',
      'Reparación, mantenimiento y conservación elementos transporte',
      'Reparación, mantenimiento y conservación elevadores',
      'Reparación, mantenimiento y conservación emisoras radio',
      'Reparación, mantenimiento y conservación equipos proceso informático',
      'Reparación, mantenimiento y conservación infraestructura y bienes naturales',
      'Reparación, mantenimiento y conservación maquinaria, instalaciones y utillaje',
      'Reparación, mantenimiento y conservación mobiliario y enseres',
      'Reparación, mantenimiento y conservación otro inmovilizado material',
      'Resarcimiento esfuerzo electrico IKEA',
      'Resto de adquisiciones de acciones del sector publico',
      'Retribuciones básicas personal eventual-Grupos Políticos',
      'Retribuciones básicas personal laboral fijo',
      'Retribuciones básicas y otras remuneraciones ',
      'Retribuciones complementarias-Grupos Políticos',
      'Retribuciones en especie',
      'Retribuciones otro personal',
      'Retribuciones personal laboral eventual',
      'Reuniones, conferencias y cursos',
      'Reurbanización C/Cantareria y C/Nueva (Actuaciones barrio Santiago)',
      'Reurbanización parque forestal La Marquesa',
      'Sector 30 San José Obrero',
      'Seguridad',
      'Seguridad Social',
      'Seguros voluntario PC',
      'Seguros-Otras prestaciones económicas a favor de empleados',
      'Servicio atención de día infantil y juvenil',
      'Servicio transporte autobuses a pedanias',
      'Servicios de recaudación a favor de la entidad',
      'Servicios técnicos (Veterinario, herrador,etc)',
      'Speed Festival',
      'Subvección deficit transporte colectivo urbano',
      'Subvención al Taxi accesible',
      'Subvención empresas privadas para fomento empleo',
      'Sueldos del grupo A1 personal funcionario',
      'Sueldos del grupo A2 personal funcionario',
      'Sueldos del Grupo C1',
      'Sueldos del grupo C2 personal funcionario',
      'Sueldos del Grupo E',
      'Suministro de gas',
      'Suministro de vestuario.',
      'Suministro material electrónico, eléctrico y telecomunicaciones',
      'Suministro munición',
      'Suministro otro material para almacen central',
      'Suministro repuestos maquinaria, utillaje y elementos',
      'Sustitución de luminaria pública a LED ELA Estella del Marqués',
      'Tabanco del Duque',
      'Teleasistencia domiciliaria',
      'Telegráficas',
      'Terrenos y bienes naturales',
      'Terrenos y bienes naturales-Actuaciones PMS',
      'Transferencia capital a familias e instituciones sin fines lucro',
      'Transferencia capital Archic. Stmo.Cristo Expiración Ermita San Telmo',
      'Transferencia capital Hermandad La Sentencia Rehabilitación Ermita La Yedra',
      'Transferencia capital Orden Padres Mercedarios Rehabilitación Basílica Merced',
      'Transferencias a Ayuntamientos',
      'Transferencias a entidades',
      'Transportes de mercancías',
      'Tributos Comunidades Autónomas',
      'Tributos Entidades locales',
      'Tributos Estatales',
      'Trienios personal funcionario',
      'Urbanización ARI F-05- La Hoyanca',
      'Urbanización Calle Varsovia',
      'Urbanización de entorno de San Juan de los Caballeros',
      'Urbanización de parcela edificio Jefatura de Policia Local',
      'Urbanización U.E. 1A18 Mreced',
      'Urbanización U.E. 4K1 Y 2M El Angel (C/Atlanta y eje)',
      'Urbanización U.E. 4S2 San Jeronimo B - 1ª Fase',
      'Urbanización UE 2T1 Armas de Santiago',
      'Urbanización vial entre UE 2T1 Armas Santiago y 1A18 Merced',
      'Valoraciones y peritajes'

    ]
    ;
      }

   ngOnInit() {
    $(function () {
        const configChosen = {
        '.chosen-select': {},
      };

      $('.chosen-select').chosen({
        disable_search_threshold: 10,
        no_results_text: 'No encuentro ',
        // width: '65%',
       });

    });

     $('#chosen1').change(function () {
       initVizEconomicos($(this).val());
     });

let vez = 0;
function initVizEconomicos(DesEco) {
  vez += 1;
  if (vez > 1) {
    viz.dispose();
  }
  const containerDiv = document.getElementById('vizContainerEconomicos'),
    // C:\Users\pc\Google Drive\Ayuntamiento\Presupuestos\2.018\Ejecucion\
    // urlEconomicos = 'https://public.tableau.com/views/1EstadoEjecucin2018Gastosporaplicaciones1-10-2018MAM/Economicoporprogramas',
    urlEconomicos = 'https://public.tableau.com/views/EstadoEjecucin2018Gastosporaplicaciones04-04-2019MAM/PorEconomico_1',

    options = {
      'DesEco': DesEco,
      hideTabs: true,
      showShareOptions: true
    };
      viz = new tableau.Viz(containerDiv, urlEconomicos, options);
    }
  }
}
